<<<<<<< HEAD
server {
    listen 80;

    location / {
        proxy_pass http://dashboard:3000;
    }

    location /api {
        proxy_pass http://api:3000;
    }
=======
server {
    listen 80;

    location / {
        proxy_pass http://dashboard:3000;
    }

    location /api {
        proxy_pass http://api:3000;
    }
>>>>>>> a0a54da391085c24c9e28ad6ab2874adc81600a7
}