server {
    listen 80;

    location / {
        proxy_pass http://dashboard:3000;
    }

    location /api {
        proxy_pass http://api:3000;
    }

    location /t/ {
        proxy_pass http://transcript:7500/t/;
    }
}