import { guildPlugin } from "vety";
import { GuildEconomyClans } from "../../data/GuildEconomyClans.js";
import { GuildEconomyCreatures } from "../../data/GuildEconomyCreatures.js";
import { GuildEconomyInventory } from "../../data/GuildEconomyInventory.js";
import { GuildEconomyMarriages } from "../../data/GuildEconomyMarriages.js";
import { GuildEconomyProfiles } from "../../data/GuildEconomyProfiles.js";
import { CommonPlugin } from "../Common/CommonPlugin.js";
import {
  BalanceCmd,
  BalanceSlashCmd,
  BattleCmd,
  BattleSlashCmd,
  BegCmd,
  BegSlashCmd,
  BuyCmd,
  BuySlashCmd,
  ClanCreateCmd,
  ClanCreateSlashCmd,
  ClanInfoCmd,
  ClanInfoSlashCmd,
  ClanJoinCmd,
  ClanJoinSlashCmd,
  ClanLeaveCmd,
  ClanLeaveSlashCmd,
  CrimeCmd,
  CrimeSlashCmd,
  DailyCmd,
  DailySlashCmd,
  DepositCmd,
  DepositSlashCmd,
  DivorceCmd,
  DivorceSlashCmd,
  EcoLbCmd,
  EcoLbSlashCmd,
  GambleCmd,
  GambleSlashCmd,
  HuntCmd,
  HuntSlashCmd,
  InventoryCmd,
  InventorySlashCmd,
  MarryCmd,
  MarrySlashCmd,
  PayCmd,
  PaySlashCmd,
  ReleaseCmd,
  RobCmd,
  RobSlashCmd,
  ShopCmd,
  ShopSlashCmd,
  SlotsCmd,
  SlotsSlashCmd,
  TeamAddCmd,
  WeeklyCmd,
  WeeklySlashCmd,
  WithdrawCmd,
  WithdrawSlashCmd,
  WorkCmd,
  WorkSlashCmd,
  ZooCmd,
  ZooSlashCmd,
} from "./commands/EconomyCmds.js";
import { EconomyPluginType, economySlashGroup, zEconomyConfig } from "./types.js";

export const EconomyPlugin = guildPlugin<EconomyPluginType>()({
  name: "economy",
  configSchema: zEconomyConfig,
  defaultOverrides: [{ level: ">=50", config: { can_manage: true } }],
  messageCommands: [
    BalanceCmd,
    WorkCmd,
    CrimeCmd,
    DailyCmd,
    WeeklyCmd,
    PayCmd,
    EcoLbCmd,
    GambleCmd,
    DepositCmd,
    WithdrawCmd,
    BegCmd,
    RobCmd,
    SlotsCmd,
    ShopCmd,
    BuyCmd,
    InventoryCmd,
    HuntCmd,
    ZooCmd,
    TeamAddCmd,
    ReleaseCmd,
    BattleCmd,
    MarryCmd,
    DivorceCmd,
    ClanCreateCmd,
    ClanJoinCmd,
    ClanLeaveCmd,
    ClanInfoCmd,
  ],
  slashCommands: [
    economySlashGroup({
      name: "economy",
      description: "Economy",
      subcommands: [
        BalanceSlashCmd,
        WorkSlashCmd,
        CrimeSlashCmd,
        DailySlashCmd,
        WeeklySlashCmd,
        PaySlashCmd,
        EcoLbSlashCmd,
        GambleSlashCmd,
        DepositSlashCmd,
        WithdrawSlashCmd,
        BegSlashCmd,
        RobSlashCmd,
        SlotsSlashCmd,
        ShopSlashCmd,
        BuySlashCmd,
        InventorySlashCmd,
        HuntSlashCmd,
        ZooSlashCmd,
        BattleSlashCmd,
        MarrySlashCmd,
        DivorceSlashCmd,
        ClanCreateSlashCmd,
        ClanJoinSlashCmd,
        ClanLeaveSlashCmd,
        ClanInfoSlashCmd,
      ],
    }),
  ],
  beforeLoad(pluginData) {
    pluginData.state.profiles = GuildEconomyProfiles.getGuildInstance(pluginData.guild.id);
    pluginData.state.inventory = GuildEconomyInventory.getGuildInstance(pluginData.guild.id);
    pluginData.state.creatures = GuildEconomyCreatures.getGuildInstance(pluginData.guild.id);
    pluginData.state.clans = GuildEconomyClans.getGuildInstance(pluginData.guild.id);
    pluginData.state.marriages = GuildEconomyMarriages.getGuildInstance(pluginData.guild.id);
  },
  beforeStart(pluginData) {
    pluginData.state.common = pluginData.getPlugin(CommonPlugin);
  },
});
